// Generated by CoffeeScript 1.6.3
(function() {
  var ColumnManipulator, RowManipulator, Transform2d, revbin_permute;

  RowManipulator = require('../row_manipulator');

  ColumnManipulator = require('../column_manipulator');

  revbin_permute = require('../utils/arrayutils').revbin_permute;

  Transform2d = (function() {
    function Transform2d(args) {
      var columnManipulator, rowManipulator;
      if (args == null) {
        args = {};
      }
      this.rImage = args.realImage;
      this.iImage = args.imaginaryImage;
      this.method = args.method || this.default_method();
      this.permutator = args.permutator || this.default_permutator();
      this.permute = args.permute || this.default_permute();
      rowManipulator = args.rowManipulator || this.default_row_manipulator();
      columnManipulator = args.columnManipulator || this.default_column_manipulator();
      this.rowm = new rowManipulator(this.rImage);
      this.colm = new columnManipulator(this.rImage);
      this.irowm = new rowManipulator(this.iImage);
      this.icolm = new columnManipulator(this.iImage);
      ({
        default_row_manipulator: function() {
          return RowManipulator;
        },
        default_column_manipulator: function() {
          return ColumnManipulator;
        },
        default_method: function() {
          return "dif";
        },
        default_permutator: function() {
          return revbin_permute;
        },
        default_permute: function() {
          return true;
        }
      });
    }

    return Transform2d;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Transform2d;
  }

}).call(this);
