// Generated by CoffeeScript 1.3.3
(function() {
  var Canvas;

  Canvas = (function() {

    function Canvas(container, canvasWidth, canvasHeight) {
      this.container = container;
      this.canvasWidth = canvasWidth;
      this.canvasHeight = canvasHeight;
      this.canvasContainer = document.getElementById(this.container);
      this.canvas = document.createElement('canvas');
      this.canvas.width = this.canvasWidth;
      this.canvas.height = this.canvasHeight;
      this.canvasContainer.appendChild(this.canvas);
      this.context = this.canvas.getContext('2d');
      this.buildImageBuffers();
    }

    Canvas.prototype.buildImageBuffers = function() {
      this.canvasData = this.context.createImageData(this.canvasWidth, this.canvasHeight);
      this.canvasBuffer = new ArrayBuffer(this.canvasData.data.length);
      this.canvasView8 = new Uint8ClampedArray(this.canvasBuffer);
      this.canvasView32 = new Uint32Array(this.canvasBuffer);
      return void 0;
    };

    Canvas.prototype.draw = function() {
      this.canvasData.data.set(this.canvasView8);
      this.context.putImageData(this.canvasData, 0, 0);
      return void 0;
    };

    return Canvas;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Canvas;
  }

}).call(this);
