// Generated by CoffeeScript 1.4.0
(function() {
  var Colormap, Gradient,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Gradient = require('./gradient');

  Colormap = (function(_super) {

    __extends(Colormap, _super);

    function Colormap() {
      Colormap.__super__.constructor.apply(this, arguments);
      this.initColors();
      this.generate();
    }

    Colormap.prototype.initColors = function() {
      var add;
      add = this.addColor;
      add(0, 0, 0, 0);
      add(255, 127, 0, 63);
      add(255, 255, 0, 127);
      return add(255, 255, 255, 255);
    };

    Colormap.prototype.getValue = function(intensity) {
      return this.gradient[intensity];
    };

    return Colormap;

  })(Gradient);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Colormap;
  }

}).call(this);
