// Generated by CoffeeScript 1.3.3
(function() {
  var colors;

  colors = {
    grayscale: function(stretchData, colorData) {
      var i, value, _i, _ref;
      for (i = _i = 0, _ref = stretchData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        value = stretchData[i];
        colorData[i] = (255 << 24) | (value << 16) | (value << 8) | value;
      }
      return void 0;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = colors;
  }

}).call(this);
