// Generated by CoffeeScript 1.4.0
(function() {
  var colors;

  colors = {
    gray: {
      type: "SAO",
      red: {
        level: [0, 1],
        intensity: [0, 1]
      },
      green: {
        level: [0, 1],
        intensity: [0, 1]
      },
      blue: {
        level: [0, 1],
        intensity: [0, 1]
      }
    },
    red: {
      type: "SAO",
      red: {
        level: [0, 1],
        intensity: [0, 1]
      },
      green: {
        level: [0, 0],
        intensity: [0, 0]
      },
      blue: {
        level: [0, 0],
        intensity: [0, 0]
      }
    },
    green: {
      type: "SAO",
      red: {
        level: [0, 0],
        intensity: [0, 0]
      },
      green: {
        level: [0, 1],
        intensity: [0, 1]
      },
      blue: {
        level: [0, 0],
        intensity: [0, 0]
      }
    },
    blue: {
      type: "SAO",
      red: {
        level: [0, 0],
        intensity: [0, 0]
      },
      green: {
        level: [0, 0],
        intensity: [0, 0]
      },
      blue: {
        level: [0, 1],
        intensity: [0, 1]
      }
    },
    heat: {
      type: "SAO",
      red: {
        level: [0, 0.34, 1],
        intensity: [0, 1, 1]
      },
      green: {
        level: [0, 1],
        intensity: [0, 1]
      },
      blue: {
        level: [0, 0.65, 0.98, 1],
        intensity: [0, 0, 1, 1]
      }
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = colors;
  }

}).call(this);
