// Generated by CoffeeScript 1.6.3
(function() {
  var ColumnManipulator;

  ColumnManipulator = (function() {
    function ColumnManipulator(args) {
      this.image = args.image;
      this.buffer = new ArrayBuffer(this.image.dataType.BYTES_PER_ELEMENT * this.image.height);
      this.column = new this.image.dataType(this.buffer);
    }

    ColumnManipulator.prototype.load = function(c) {
      var column, data, imageWidth, y;
      column = this.column;
      data = this.image.data;
      imageWidth = this.image.width;
      y = this.image.height;
      while (y--) {
        column[y] = data[c + y * imageWidth];
      }
      return void 0;
    };

    ColumnManipulator.prototype.save = function(c) {
      var column, data, imageWidth, y;
      column = this.column;
      data = this.image.data;
      imageWidth = this.image.width;
      y = this.image.height;
      while (y--) {
        data[c + y * imageWidth] = column[y];
      }
      return void 0;
    };

    return ColumnManipulator;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ColumnManipulator;
  }

}).call(this);
