// Generated by CoffeeScript 1.6.3
(function() {
  var Galactic;

  Galactic = {};

  Galactic.VERSION = '0.0.1';

  Galactic.Image = require('./image');

  Galactic.Display = require('./display');

  Galactic.ImageFormatter = require('./image_formatter');

  Galactic.ImagePadder = require('./image_padder');

  Galactic.stretches = require('./stretches');

  Galactic.colors = require('./colors');

  Galactic.Model = require('./model');

  Galactic.Modeler = require('./modeler');

  Galactic.Sersic = require('./sersic');

  Galactic.Residual = require('./residual');

  Galactic.PSFConvolutor = require('./psf_convolutor');

  Galactic.utils = {};

  Galactic.utils.arrayutils = require('./utils/arrayutils');

  Galactic.utils.bitswap = require('./utils/bitswap');

  Galactic.utils.bitreverse = require('./utils/bitreverse');

  Galactic.Gradient = require('./gradient');

  Galactic.Colormap = require('./colormap');

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Galactic;
  }

}).call(this);
