// Generated by CoffeeScript 1.3.3
(function() {
  var Galactic;

  Galactic = {};

  Galactic.VERSION = '0.0.1';

  Galactic.Display = require('./display');

  Galactic.Canvas = require('./canvas');

  Galactic.StretchProcessor = require('./stretch_processor');

  Galactic.ColorProcessor = require('./color_processor');

  Galactic.Model = require('./model');

  Galactic.Residual = require('./residual');

  Galactic.utils = require('./utils');

  Galactic.stretches = require('./stretches');

  Galactic.colors = require('./colors');

  Galactic.models = require('./models');

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Galactic;
  }

}).call(this);
