// Generated by CoffeeScript 1.4.0
(function() {
  var Gradient;

  Gradient = (function() {

    function Gradient() {
      this.buffer = new ArrayBuffer(256);
      this.gradient = new Uint8ClampedArray(this.buffer);
      this.entries = [];
    }

    Gradient.prototype.add = function(level, intensity) {
      var entry;
      entry = {
        level: ~~(255 * level),
        intensity: ~~(255 * intensity)
      };
      return this.entries.push(entry);
    };

    Gradient.prototype.build = function() {
      var entries, entry1, entry2, gradient, i, intensity1, intensity2, invRange, j, level1, level2, range, value, _results;
      gradient = this.gradient;
      entries = this.entries;
      i = entries.length - 1;
      _results = [];
      while (i--) {
        entry1 = entries[i];
        entry2 = entries[i + 1];
        level1 = entry1.level;
        level2 = entry2.level;
        intensity1 = entry1.intensity;
        intensity2 = entry2.intensity;
        range = level2 - level1;
        invRange = 1 / range;
        j = range + 1;
        _results.push((function() {
          var _results1;
          _results1 = [];
          while (j--) {
            value = (intensity2 - intensity1) * j * invRange + intensity1;
            _results1.push(gradient[level1 + j] = ~~value);
          }
          return _results1;
        })());
      }
      return _results;
    };

    return Gradient;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Gradient;
  }

}).call(this);
