// Generated by CoffeeScript 1.6.3
(function() {
  var Image;

  Image = (function() {
    function Image(args) {
      if (args == null) {
        args = {};
      }
      this.width = args.width || this.default_width();
      this.height = args.height || this.default_height();
      this.dataType = args.dataType || this.default_data_type();
      this.buffer = new ArrayBuffer(this.width * this.height * this.dataType.BYTES_PER_ELEMENT);
      this.data = new this.dataType(this.buffer);
      this.post_initialize(args);
    }

    Image.prototype.post_initialize = function(args) {
      return null;
    };

    Image.prototype.default_data_type = function() {
      return Float64Array;
    };

    Image.prototype.default_width = function() {
      return 512;
    };

    Image.prototype.default_height = function() {
      return 512;
    };

    return Image;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Image;
  }

}).call(this);
