// Generated by CoffeeScript 1.3.3
(function() {
  var Image;

  Image = (function() {

    function Image(width, height) {
      this.width = width;
      this.height = height;
      this.buffer = new ArrayBuffer(this.width * this.height * 4);
      this.data = new Float32Array(this.buffer);
    }

    return Image;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Image;
  }

}).call(this);
