// Generated by CoffeeScript 1.4.0
(function() {
  var Image, Model,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Image = require('./image');

  Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.post_initialize = function(args) {
      this.name = args.name;
      this.enabled = args.enabled != null ? args.enabled : true;
      this.stale = args.stale != null ? args.stale : true;
      return this.set_up_parameters(args);
    };

    Model.prototype.set_up_parameters = function(args) {
      return null;
    };

    Model.prototype.enable = function() {
      return this.enabled = true;
    };

    Model.prototype.disable = function() {
      return this.enabled = false;
    };

    Model.prototype.update_params = function(args) {
      if (args == null) {
        args = {};
      }
      this.stale = true;
      return this.on_params_update(args);
    };

    Model.prototype.on_params_update = function(args) {
      return null;
    };

    Model.prototype.build = function() {
      this.stale = false;
      return this.calculate();
    };

    Model.prototype.calculate = function() {
      return null;
    };

    return Model;

  })(Image);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Model;
  }

}).call(this);
