// Generated by CoffeeScript 1.4.0
(function() {
  var Image, Residual,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Image = require('./image');

  Residual = (function(_super) {

    __extends(Residual, _super);

    function Residual(width, height) {
      this.width = width;
      this.height = height;
      Residual.__super__.constructor.call(this, this.width, this.height);
    }

    Residual.prototype.build = function(fitsData, modelData) {
      var data, i;
      data = this.data;
      i = this.width * this.height;
      while (i--) {
        data[i] = fitsData[i] - modelData[i];
      }
      return void 0;
    };

    return Residual;

  })(Image);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Residual;
  }

}).call(this);
