// Generated by CoffeeScript 1.4.0
(function() {
  var Image, Residual,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Image = require('./image');

  Residual = (function(_super) {

    __extends(Residual, _super);

    function Residual(width, height) {
      this.width = width;
      this.height = height;
      Residual.__super__.constructor.call(this, this.width, this.height);
    }

    Residual.prototype.build = function(fitsData, modelData) {
      var index, _i, _ref;
      for (index = _i = 0, _ref = this.width * this.height; 0 <= _ref ? _i <= _ref : _i >= _ref; index = 0 <= _ref ? ++_i : --_i) {
        this.data[index] = fitsData[index] - modelData[index];
      }
      return void 0;
    };

    return Residual;

  })(Image);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Residual;
  }

}).call(this);
