// Generated by CoffeeScript 1.6.3
(function() {
  var Image, Residual, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Image = require('./image');

  Residual = (function(_super) {
    __extends(Residual, _super);

    function Residual() {
      _ref = Residual.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Residual.prototype.post_initialize = function(args) {
      this.fitsData = args.fitsData;
      return this.modelData = args.modelData;
    };

    Residual.prototype.build = function() {
      var fits, i, model, residual;
      residual = this.data;
      fits = this.fitsData;
      model = this.modelData;
      i = this.width * this.height;
      while (i--) {
        residual[i] = fits[i] - model[i];
      }
      return void 0;
    };

    return Residual;

  })(Image);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Residual;
  }

}).call(this);
