// Generated by CoffeeScript 1.4.0
(function() {
  var RowManipulator;

  RowManipulator = (function() {

    function RowManipulator(image) {
      this.image = image;
      this.buffer = new ArrayBuffer(this.image.dataType.BYTES_PER_ELEMENT * this.image.width);
      this.row = new this.image.dataType(this.buffer);
    }

    RowManipulator.prototype.load = function(r) {
      var data, imageWidth, offset, row, x;
      row = this.row;
      data = this.image.data;
      imageWidth = this.image.width;
      offset = r * imageWidth;
      x = imageWidth;
      while (x--) {
        row[x] = data[x + offset];
      }
      return void 0;
    };

    RowManipulator.prototype.save = function(r) {
      var data, imageWidth, offset, row, x;
      row = this.row;
      data = this.image.data;
      imageWidth = this.image.width;
      offset = r * imageWidth;
      x = imageWidth;
      while (x--) {
        data[x + offset] = row[x];
      }
      return void 0;
    };

    return RowManipulator;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = RowManipulator;
  }

}).call(this);
