// Generated by CoffeeScript 1.4.0
(function() {
  var Model, Sersic,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('./model');

  Sersic = (function(_super) {

    __extends(Sersic, _super);

    function Sersic(name, width, height) {
      this.name = name;
      this.width = width;
      this.height = height;
      Sersic.__super__.constructor.call(this, this.name, this.width, this.height);
      this.initDefaultParams();
      this.initParamArray();
    }

    Sersic.prototype.initParamArray = function() {
      return this.paramArray = ['centerX', 'centerY', 'angle', 'axisRatio', 'effRadius', 'intensity', 'n'];
    };

    Sersic.prototype.initDefaultParams = function() {
      return this.params = {
        centerX: 31.5,
        centerY: 42,
        angle: 0,
        axisRatio: 1,
        effRadius: 6,
        intensity: 2.3,
        n: 1
      };
    };

    Sersic.prototype.build = function() {
      var cos, cx, cy, exponent, height, intensity, invAxisRatio, invEffRadius, invN, n, norm, r, r_x, r_y, sin, width, x, y, _i, _j, _ref, _ref1;
      Sersic.__super__.build.apply(this, arguments);
      n = this.params.n;
      invN = 1 / n;
      norm = n * Math.exp(0.6950 - 0.1789 * invN);
      sin = Math.sin(this.params.angle);
      cos = Math.cos(this.params.angle);
      invAxisRatio = 1 / this.params.axisRatio;
      invEffRadius = this.params.effRadius;
      invN = 1 / this.params.n;
      intensity = this.params.intensity;
      cx = this.params.centerX;
      cy = this.params.centerY;
      width = this.width;
      height = this.height;
      x = width;
      for (x = _i = 0, _ref = width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        for (y = _j = 0, _ref1 = height - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
          r_x = (x - cx) * cos + (y - cy) * sin;
          r_y = ((y - cy) * cos - (x - cx) * sin) * invAxisRatio;
          r = Math.sqrt(r_x * r_x + r_y * r_y);
          exponent = norm * Math.pow(r * invEffRadius, invN) - 1;
          this.data[y * width + x] = intensity * Math.exp(-exponent);
        }
      }
      return void 0;
    };

    return Sersic;

  })(Model);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Sersic;
  }

}).call(this);
