// Generated by CoffeeScript 1.3.3
(function() {
  var StretchProcessor;

  StretchProcessor = function(algorithm) {
    return {
      process: function(imageData, scaleData) {
        return algorithm(imageData, scaleData);
      }
    };
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = StretchProcessor;
  }

}).call(this);
