// Generated by CoffeeScript 1.3.3
(function() {
  var stretches;

  stretches = {
    linear: function(imageData, stretchData, min, max) {
      var i, index, range, _i, _ref;
      range = max - min;
      index = 0;
      for (i = _i = 0, _ref = stretchData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        stretchData[i] = ~~(255 * ((imageData[i] - min) / range));
      }
      return void 0;
    },
    log: function(imageData, stretchData, min, max) {
      var i, max_log, range, _i, _ref;
      range = max - min;
      max_log = Math.log(range) / Math.LN10;
      for (i = _i = 0, _ref = stretchData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        stretchData[i] = ~~(255 * ((Math.log(imageData[i] - min + 1) / Math.LN10) / max_log));
      }
      return void 0;
    },
    power: function(imageData, stretchData, min, max) {
      var i, max_power, range, value, _i, _ref;
      range = max - min;
      max_power = range * range;
      for (i = _i = 0, _ref = stretchData.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        value = imageData[i] - min;
        stretchData[i] = ~~(255 * ((value * value) / max_power));
      }
      return void 0;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = stretches;
  }

}).call(this);
