// Generated by CoffeeScript 1.4.0
(function() {
  var utils;

  utils = {
    max: function(array) {
      var i, length, max, _i, _ref;
      max = -Infinity;
      length = array.length;
      for (i = _i = 0, _ref = length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (array[i] > max) {
          max = array[i];
        }
      }
      return max;
    },
    min: function(array) {
      var i, length, min, _i, _ref;
      min = Infinity;
      length = array.length;
      for (i = _i = 0, _ref = length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (array[i] < min) {
          min = array[i];
        }
      }
      return min;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = utils;
  }

}).call(this);
