// Generated by CoffeeScript 1.4.0
(function() {
  var utils;

  utils = {
    max: function(array) {
      var i, max;
      max = -Infinity;
      i = array.length;
      while (i--) {
        if (array[i] > max) {
          max = array[i];
        }
      }
      return max;
    },
    min: function(array) {
      var i, min;
      min = Infinity;
      i = array.length;
      while (i--) {
        if (array[i] < min) {
          min = array[i];
        }
      }
      return min;
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = utils;
  }

}).call(this);
